- lib/spi.ex
- lib/spi/spi_nif.ex
- src/spi_nif.c
- src/spi_nif.h
Per review of last SPI pull request:
Abandon code to maintain resource list in the NIF
Switch to using references instead of file descriptors, to identify open channels for reading and writing
Return ":ok" tuple with data, on successful read.
Follow C code standards, 
Format code
> Use references when reading and writing to SPI bus

- lib/spi/spi_nif.ex
It turns out that Erlang already has a reasonable error message. Here's
what I get:
```
08:20:29.252 [warn]  The on_load function for module Elixir.ElixirCircuits.SPI.Nif returned:
{:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/fhunleth/nerves/circuits/spi/_build/dev/lib/spi/priv/spi_nif.so, 2): image not found\''}}
```
> Remove log message when NIF fails to load

- .gitignore
- README.md
- lib/spi.ex
- lib/spi/spi_nif.ex
- mix.exs
- src/spi_nif.c
- src/spi_nif.h
This also adds back the NIF check so that its possible to build docs on OSX.
> Rename to circuits_spi

- src/spi_nif.c
Casting pointers to bigger types can result in unaligned reads which
might not work depending on the processor. This fixes the issue by
passing pointers of the expected type (no cast) and then losing bits via
conversions later.
> Remove cast that could break

- README.md
- lib/spi.ex
Add Erlang friendly bindings like we already did for I2C.  
Update README:  Mention Erlang bindings.  Add debugging info, similar to what is already in I2C README.
> Add Erlang bindings

- Makefile
- lib/spi.ex
- lib/spi/spi_nif.ex
- src/hal_spidev.c
- src/hal_stub.c
- src/spi_nif.c
- src/spi_nif.h
- test/circuits_spi_test.exs
The immediate advantage to this is that it enables compilation and the
ability to exercise the NIF on OSX.
> Refactor C code to support multiple HALs

- .circleci/config.yml
- Makefile
- README.md
- lib/spi.ex
- lib/spi/spi_nif.ex
- mix.exs
- mix.lock
- src/hal_spidev.c
- src/hal_stub.c
- src/spi_nif.c
- src/spi_nif.h
- test/circuits_spi_test.exs
This renames `device_names` to `bus_names` to be consistent with I2C naming. It also pulls in the Dialyzer and spec updates from I2C.
The idea is to merge this PR after #11.
> Naming and specs

- .circleci/config.yml
- Makefile
- mix.exs
- mix.lock
This PR pulls in a set of changes from circuits_gpio to fix the issue where you switch MIX_TARGETs and the C source isn't recompiled.
> Use separate build directories for C compilation

- src/spi_nif.c
This fixes a file handle leak whenever GC collected a SPI bus reference.
> Add destructor to close file handle to SPI bus

- src/spi_nif.c
- src/spi_nif.h
ErlNifBinary was being directly set even though this is not allowed.
This updates the code to properly allocate the binary. This fixes a
segfault on Raspbian (and most likely everywhere else)
Fixes #23
>  Properly allocated binaries in NIF 

- .circleci/config.yml
- mix.exs
- mix.lock
I was attempting to get Elixir Circuits to work on Raspbian Stretch using the default Elixir and Erlang versions supplied by the Raspberry Pi Foundation. This PR doesn't get us there. Raspbian currently supports Erlang 19.1 and Elixir 1.3.3. Erlang 19.1 needs more works since we use dirty NIFs and Circuits.GPIO is even more involved in what needs to change for pre-OTP 20 Erlang. Elixir is less of an issue, but I quit with Elixir 1.4, since Elixir 1.3 seemed to expect OTP 19 (but I might have messed up). 
I feel like the work to make astyle optional, the CircleCI config cleanup, and support for Elixir 1.4 are reasonable to have going forward.
> Support older Elixir versions/make astyle optional

- README.md
This also reorders the badges so that the hexpm ones are first. Those seem like the more important ones for most people finding this project.
> Add badge and link to API docs

- lib/spi.ex
- lib/spi/spi_nif.ex
- src/hal_spidev.c
- src/hal_stub.c
- src/spi_nif.c
- src/spi_nif.h
- test/circuits_spi_test.exs
Linux put the maximum buffer size of the SPI device at `/sys/module/spidev/parameters/bufsiz`. 
The amount of data in a single transfer must be less than or equal to this number, otherwise, `ioctl` will return a negative value indicating errors. Subsequently, users will get `{:error, :transfer_failed}` in Erlang/Elixir.
This PR added a `max_transfer_size` function to retrieve the maximum buffer size. If `/sys/module/spidev/parameters/bufsiz` is not available, then it returns ~`:unknown`~ `4096`, a safe minimum size in Linux.
> Add `max_transfer_size/0`

- src/spi_nif.c
Tested on Raspberry Pi 4 SPI@125MHz, everything works as expected.
> mark `spi_transfer` as `ERL_NIF_DIRTY_JOB_IO_BOUND`

- lib/spi.ex
- src/hal_spidev.c
While this isn't mentioned in the docs, now that there's commandline
completion, it's really easy to use it to find the bus. That means that
`open/2` can be passed `"/dev/spidev0.0"`, etc. Rather than returning
access denied, just open the device.
> Allow users to pass in /dev/spidev*

- Makefile
This "fixes" the following:
```
CC hal_spidev.o
src/hal_spidev.c: In function 'hal_spi_open':
src/hal_spidev.c:83:19: warning: overflow in conversion from 'long unsigned int' to 'int' changes value from '2147576577' to '-2147390719' [-Woverflow]
83 |     if (ioctl(fd, SPI_IOC_RD_MODE, &mode) == 0) {
|                   ^~~~~~~~~~~~~~~
src/hal_spidev.c:92:19: warning: overflow in conversion from 'long unsigned int' to 'int' changes value from '2147576579' to '-2147390717' [-Woverflow]
92 |     if (ioctl(fd, SPI_IOC_RD_BITS_PER_WORD, &bits_per_word) == 0) {
|                   ^~~~~~~~~~~~~~~~~~~~~~~~
src/hal_spidev.c:101:19: warning: overflow in conversion from 'long unsigned int' to 'int' changes value from '2147773188' to '-2147194108' [-Woverflow]
101 |     if (ioctl(fd, …
```
> Disable gcc overflow warning on Linux

- lib/spi.ex
- lib/spi/spi_nif.ex
- src/hal_spidev.c
- src/hal_stub.c
- src/spi_nif.c
- src/spi_nif.h
- test/circuits_spi_test.exs
This adds the `:lsb_first` option to indicate that the least significant
bit is transferred first rather than the normal way. If the SPI hardware
doesn't support bit reversal, do it in software. This is necessary on
the Raspberry Pi.
> Add support for reversing bit order

- lib/spi.ex
- test/circuits_spi_test.exs
This is a very minimal update to allow iodata to be used for
convenience. It doesn't enable better performance. I left a note about
my performance doubts. It would be interesting to see what happens in
the future for users with larger SPI transfers than me.
Fixes #52.
> Support passing iodata to transfer/2

- lib/spi.ex
This is a minor enhancement. I thought it would be nice to have an error-raising variant of [`transfer/2`](https://hexdocs.pm/circuits_spi/Circuits.SPI.html#transfer/2) just like [`circuits_i2c`](https://hexdocs.pm/circuits_i2c/Circuits.I2C.html) does.
> Add transfer!/2

- c_src/hal_spidev.c
- c_src/hal_stub.c
- c_src/spi_nif.c
- lib/spi.ex
This has the following changes:
1. Change filename to be an Elixir string rather than an Erlang one in
the NIF. There's no external API change.
2. Push iodata to binary conversion down to C. The performance is
roughly the same as flatting in Elixir, but lowering it in the stack
will come in handy for the future swappable backend change.
3. Various minor code style changes to look more like circuits_i2c C.
While circuits_i2c switched to a one C file, that was harder to do here
and not introduce a lot of compatibility header files to compile on
MacOS.
> Port NIF updates from circuits_i2c

- lib/spi/spi_nif.ex
This change moves the NIF load from the time at which the module is
loaded to the time when SPI actually is used.
The primary motivation for doing this is to defer native code crashes
from happening at load time to the time of first use. Load time is
harder to debug and sometimes its not clear which NIF caused the crash.
The calls to `apply` get around some complexity with ignoring Dialyzer
warnings. Dialyzer can't figure out that the recursive looking call
actually invokes the NIF code.
> Defer loading the NIF until opening a SPI bus (v1.x branch)

- lib/spi/spi_nif.ex
- test/circuits_spi_test.exs
Previously the second load would fail and in this case was able to cause
a segfault.
> Fix race condition when loading the NIF

- mix.exs
It turns out that people sometimes have MIX_TARGET set when they're not
compiling for Nerves. On MacOS which doesn't support cdev, this causes
the following error:
```
==> circuits_spi
"**** CIRCUITS_SPI_BACKEND set to [normal] ****"
Makefile:44: *** Circuits.SPI Linux cdev backend is not supported on non-Linux platforms. Review circuits_spi backend configuration or report an issue if improperly detected..  Stop.
could not compile dependency :circuits_spi, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile circuits_spi --force", update it with "mix deps.update circuits_spi" or clean it with "mix deps.clean circuits_spi"
```
This is pretty confusing. This change makes the Nerves detection smarter
by first checking the …
> Improve target detection for building spi-dev

- lib/spi.ex
An error is printed to standard error by Linux Kernel when hardware doesn't support the LSB-first mode. It is benign in our context since Circuits.SPI handles it automatically; however, currently there's no way of fixing this since Linux Kernel doesn't have an API to check support for the LSB first mode without printing that error message. The way that Linux Kernel figures out whether the LSB first mode is supported prints that error message.
Related: https://github.com/fhunleth/binary_clock/pull/3
> Explain lsb-first-related error message
